In [2]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop('species', axis=1)
y =df['species']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [12]:
model_knn.score(X_test, y_test)

1.0

In [13]:
from sklearn.svm import SVC

In [14]:
model_svm = SVC(gamma='auto')

In [15]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [16]:
model_svm.score(X_test, y_test)

1.0

In [17]:
# Now lets use the grid search

In [18]:
from sklearn.model_selection import GridSearchCV

In [19]:
classifier = GridSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel': ['rbf', 'linear'],
    
},cv=5, return_train_score=False)

In [20]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [21]:
classifier.cv_results_

{'mean_fit_time': array([0.00297356, 0.00202832, 0.00234818, 0.0037468 , 0.00220623,
        0.00224543, 0.00164385, 0.00254836]),
 'std_fit_time': array([3.74098669e-03, 1.94351947e-05, 1.43963182e-03, 1.76655292e-03,
        3.95026206e-04, 3.31326428e-03, 2.17713385e-03, 1.58188034e-03]),
 'mean_score_time': array([0.00172358, 0.00171895, 0.00083041, 0.00114522, 0.00123706,
        0.00041494, 0.00236707, 0.00244398]),
 'std_score_time': array([0.00205982, 0.00088085, 0.00101783, 0.00094296, 0.0012122 ,
        0.00082989, 0.00254898, 0.00396078]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7])}

In [22]:
result = pd.DataFrame(classifier.cv_results_)

In [23]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002974,0.003741,0.001724,0.002060,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002028,0.000019,0.001719,0.000881,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002348,0.001440,0.000830,0.001018,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003747,0.001767,0.001145,0.000943,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002206,0.000395,0.001237,0.001212,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002245,0.003313,0.000415,0.000830,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.001644,0.002177,0.002367,0.002549,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002548,0.001582,0.002444,0.003961,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [24]:
result[['param_C','param_kernel','mean_test_score' ]]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667
6      30          rbf         0.960000
7      30       linear         0.960000

In [25]:
from sklearn.neighbors import kneighbors_graph

In [26]:
model_knn = KNeighborsClassifier()

In [27]:
param_grid = {
    'n_neighbors':[2,5,7,8],
    'weights':['uniform'],
    'leaf_size':[30],
    'metric':['minkowski']
}

In [28]:
classifier2 = GridSearchCV(
    model_knn,
    param_grid,
    cv= 5,
    scoring='accuracy'
)

In [29]:
classifier2.fit(X_train,y_train )

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'leaf_size': [30], 'metric': ['minkowski'],
                         'n_neighbors': [2, 5, 7, 8], 'weights': ['uniform']},
             scoring='accuracy')

In [30]:
classifier2.cv_results_

{'mean_fit_time': array([0.00149431, 0.00339508, 0.00099049, 0.00162072]),
 'std_fit_time': array([0.00188749, 0.00343078, 0.00095517, 0.00202686]),
 'mean_score_time': array([0.00588012, 0.00291381, 0.00306587, 0.00421629]),
 'std_score_time': array([0.00255151, 0.00179567, 0.00188148, 0.00440853]),
 'param_leaf_size': masked_array(data=[30, 30, 30, 30],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_metric': masked_array(data=['minkowski', 'minkowski', 'minkowski', 'minkowski'],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_n_neighbors': masked_array(data=[2, 5, 7, 8],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_weights': masked_array(data=['uniform', 'uniform', 'uniform', 'uniform'],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'leaf_size': 30,
   'metric': 'minkowski',
   'n_neighbors': 2,
   'weights': 'uniform'},
  {'leaf_size': 30,
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'leaf_size': 30,
   'metric': 'minkowski',
   'n_neighbors': 7,
   'weights': 'uniform'},
  {'leaf_size': 30,
   'metric': 'minkowski',
   'n_neighbors': 8,
   'weights': 'uniform'}],
 'split0_test_score': array([0.9, 0.9, 0.9, 0.9]),
 'split1_test_score': array([0.85, 0.9 , 0.9 , 0.9 ]),
 'split2_test_score': array([0.9 , 0.9 , 0.9 , 0.95]),
 'split3_test_score': array([1., 1., 1., 1.]),
 'split4_test_score': array([0.95, 0.95, 0.95, 0.95]),
 'mean_test_score': array([0.92, 0.93, 0.93, 0.94]),
 'std_test_score': array([0.0509902 , 0.04      , 0.04      , 0.03741657]),
 'rank_test_score': array([4, 2, 2, 1])}

In [31]:
result = pd.DataFrame(classifier2.cv_results_)

In [32]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_leaf_size,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001494,0.001887,0.005880,0.002552,30,minkowski,2,uniform,"{'leaf_size': 30, 'metric': 'minkowski', 'n_ne...",0.9,0.85,0.90,1.0,0.95,0.92,0.050990,4
1,0.003395,0.003431,0.002914,0.001796,30,minkowski,5,uniform,"{'leaf_size': 30, 'metric': 'minkowski', 'n_ne...",0.9,0.90,0.90,1.0,0.95,0.93,0.040000,2
2,0.000990,0.000955,0.003066,0.001881,30,minkowski,7,uniform,"{'leaf_size': 30, 'metric': 'minkowski', 'n_ne...",0.9,0.90,0.90,1.0,0.95,0.93,0.040000,2
3,0.001621,0.002027,0.004216,0.004409,30,minkowski,8,uniform,"{'leaf_size': 30, 'metric': 'minkowski', 'n_ne...",0.9,0.90,0.95,1.0,0.95,0.94,0.037417,1

In [33]:
result[['param_metric', 'mean_test_score']]

  param_metric  mean_test_score
0    minkowski             0.92
1    minkowski             0.93
2    minkowski             0.93
3    minkowski             0.94

In [34]:
from sklearn.model_selection import RandomizedSearchCV

In [36]:
classifier_r= RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf', 'linear'],
    
},n_iter=4,cv=5, return_train_score=False)

In [37]:
classifier_r.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [38]:
result =pd.DataFrame(classifier_r.cv_results_)

In [39]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003037,0.003345,0.001203,0.000982,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000887,0.001103,0.001041,0.001588,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,3
2,0.000771,0.000645,0.001573,0.001794,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,3
3,0.001101,0.000489,0.000601,0.000491,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,2

In [40]:
result[['param_C', 'param_kernel', 'mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1      30       linear         0.960000
2      30          rbf         0.960000
3      20          rbf         0.966667