In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset("titanic")

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [7]:
df.drop(['deck', 'embark_town','alive', 'alone'], axis=1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True

In [8]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [9]:
df['age'].fillna(df['age'].mean(), inplace =True)

C:\Users\py064\AppData\Local\Temp\ipykernel_10004\3252251236.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(), inplace =True)

In [10]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [11]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
df = df.drop(['deck', 'embark_town', 'alive', 'alone'], axis=1)

In [13]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True

In [14]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age           0
sibsp         0
parch         0
fare          0
embarked      2
class         0
who           0
adult_male    0
dtype: int64

In [15]:
df.dropna(subset=["embarked"], inplace=True)

In [16]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True

In [17]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()

In [18]:
df['sex'] = le.fit_transform(df['sex'])

In [19]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male
0,0,3,1,22.000000,1,0,7.2500,S,Third,man,True
1,1,1,0,38.000000,1,0,71.2833,C,First,woman,False
2,1,3,0,26.000000,0,0,7.9250,S,Third,woman,False
3,1,1,0,35.000000,1,0,53.1000,S,First,woman,False
4,0,3,1,35.000000,0,0,8.0500,S,Third,man,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,S,Second,man,True
887,1,1,0,19.000000,0,0,30.0000,S,First,woman,False
888,0,3,0,29.699118,1,2,23.4500,S,Third,woman,False
889,1,1,1,26.000000,0,0,30.0000,C,First,man,True
890,0,3,1,32.000000,0,0,7.7500,Q,Third,man,True

In [20]:
df['embarked' ] = le.fit_transform(df['embarked'])

In [21]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male
0,0,3,1,22.000000,1,0,7.2500,2,Third,man,True
1,1,1,0,38.000000,1,0,71.2833,0,First,woman,False
2,1,3,0,26.000000,0,0,7.9250,2,Third,woman,False
3,1,1,0,35.000000,1,0,53.1000,2,First,woman,False
4,0,3,1,35.000000,0,0,8.0500,2,Third,man,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,2,Second,man,True
887,1,1,0,19.000000,0,0,30.0000,2,First,woman,False
888,0,3,0,29.699118,1,2,23.4500,2,Third,woman,False
889,1,1,1,26.000000,0,0,30.0000,0,First,man,True
890,0,3,1,32.000000,0,0,7.7500,1,Third,man,True

In [22]:
df = pd.get_dummies(df)

In [23]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,class_First,class_Second,class_Third,who_child,who_man,who_woman
0,0,3,1,22.000000,1,0,7.2500,2,True,False,False,True,False,True,False
1,1,1,0,38.000000,1,0,71.2833,0,False,True,False,False,False,False,True
2,1,3,0,26.000000,0,0,7.9250,2,False,False,False,True,False,False,True
3,1,1,0,35.000000,1,0,53.1000,2,False,True,False,False,False,False,True
4,0,3,1,35.000000,0,0,8.0500,2,True,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,2,True,False,True,False,False,True,False
887,1,1,0,19.000000,0,0,30.0000,2,False,True,False,False,False,False,True
888,0,3,0,29.699118,1,2,23.4500,2,False,False,False,True,False,False,True
889,1,1,1,26.000000,0,0,30.0000,0,True,True,False,False,False,True,False
890,0,3,1,32.000000,0,0,7.7500,1,True,False,False,True,False,True,False

In [24]:
df =df.astype(int)

In [25]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,class_First,class_Second,class_Third,who_child,who_man,who_woman
0,0,3,1,22,1,0,7,2,1,0,0,1,0,1,0
1,1,1,0,38,1,0,71,0,0,1,0,0,0,0,1
2,1,3,0,26,0,0,7,2,0,0,0,1,0,0,1
3,1,1,0,35,1,0,53,2,0,1,0,0,0,0,1
4,0,3,1,35,0,0,8,2,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,2,1,0,1,0,0,1,0
887,1,1,0,19,0,0,30,2,0,1,0,0,0,0,1
888,0,3,0,29,1,2,23,2,0,0,0,1,0,0,1
889,1,1,1,26,0,0,30,0,1,1,0,0,0,1,0
890,0,3,1,32,0,0,7,1,1,0,0,1,0,1,0

In [26]:
x = df.drop("survived", axis= 1)
y = df["survived"]

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
   x, y, test_size=0.2, random_state=42)

In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, y_train)

c:\Users\py064\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [29]:
y_pred =model.predict(X_test)

In [30]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [31]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int32

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [33]:
accuracy_score(y_test, y_pred)

0.8202247191011236

In [34]:
confusion_matrix(y_test, y_pred)

array([[91, 18],
       [14, 55]], dtype=int64)

In [35]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.83      0.85       109
           1       0.75      0.80      0.77        69

    accuracy                           0.82       178
   macro avg       0.81      0.82      0.81       178
weighted avg       0.82      0.82      0.82       178

In [36]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,class_First,class_Second,class_Third,who_child,who_man,who_woman
0,0,3,1,22,1,0,7,2,1,0,0,1,0,1,0
1,1,1,0,38,1,0,71,0,0,1,0,0,0,0,1
2,1,3,0,26,0,0,7,2,0,0,0,1,0,0,1
3,1,1,0,35,1,0,53,2,0,1,0,0,0,0,1
4,0,3,1,35,0,0,8,2,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,2,1,0,1,0,0,1,0
887,1,1,0,19,0,0,30,2,0,1,0,0,0,0,1
888,0,3,0,29,1,2,23,2,0,0,0,1,0,0,1
889,1,1,1,26,0,0,30,0,1,1,0,0,0,1,0
890,0,3,1,32,0,0,7,1,1,0,0,1,0,1,0

Feature Scalling

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
le = StandardScaler()

In [39]:
X_train_scale = le.fit_transform(X_train)
X_test_scale = le.fit_transform(X_test)

In [40]:
X_test_scale
X_train_scale

array([[-1.58410418, -1.40530972, -0.58667407, ..., -0.32254808,
        -1.25542302,  1.54981092],
       [ 0.8122747 , -1.40530972, -0.05336323, ..., -0.32254808,
        -1.25542302,  1.54981092],
       [ 0.8122747 ,  0.71158691,  0.17519856, ..., -0.32254808,
         0.79654426, -0.64524   ],
       ...,
       [-1.58410418, -1.40530972,  1.39419477, ..., -0.32254808,
        -1.25542302,  1.54981092],
       [ 0.8122747 , -1.40530972, -0.66286134, ..., -0.32254808,
        -1.25542302,  1.54981092],
       [ 0.8122747 ,  0.71158691,  0.25138582, ..., -0.32254808,
         0.79654426, -0.64524   ]])

In [41]:
from sklearn.neighbors import KNeighborsClassifier

In [42]:
knn_model = KNeighborsClassifier(n_neighbors= 5)

In [43]:
knn_model.fit(X_train_scale, y_train)

KNeighborsClassifier()

In [44]:
y_pred_knn =knn_model.predict(X_test_scale)

In [45]:
y_pred_knn

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0])

In [46]:
accuracy_score(y_test, y_pred_knn)

0.7752808988764045

In [47]:
X_train

,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,class_First,class_Second,class_Third,who_child,who_man,who_woman
708,1,0,22,0,0,151,2,0,1,0,0,0,0,1
240,3,0,29,1,0,14,0,0,0,0,1,0,0,1
382,3,1,32,0,0,7,2,1,0,0,1,0,1,0
792,3,0,29,8,2,69,2,0,0,0,1,0,0,1
683,3,1,14,5,2,46,2,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,3,1,29,0,0,7,2,1,0,0,1,0,1,0
271,3,1,25,0,0,0,2,1,0,0,1,0,1,0
862,1,0,48,0,0,25,2,0,1,0,0,0,0,1
436,3,0,21,2,2,34,2,0,0,0,1,0,0,1
103,3,1,33,0,0,8,2,1,0,0,1,0,1,0

In [48]:
X_train_scale

array([[-1.58410418, -1.40530972, -0.58667407, ..., -0.32254808,
        -1.25542302,  1.54981092],
       [ 0.8122747 , -1.40530972, -0.05336323, ..., -0.32254808,
        -1.25542302,  1.54981092],
       [ 0.8122747 ,  0.71158691,  0.17519856, ..., -0.32254808,
         0.79654426, -0.64524   ],
       ...,
       [-1.58410418, -1.40530972,  1.39419477, ..., -0.32254808,
        -1.25542302,  1.54981092],
       [ 0.8122747 , -1.40530972, -0.66286134, ..., -0.32254808,
        -1.25542302,  1.54981092],
       [ 0.8122747 ,  0.71158691,  0.25138582, ..., -0.32254808,
         0.79654426, -0.64524   ]])

In [49]:
from sklearn.naive_bayes import GaussianNB

In [50]:
model_NB = GaussianNB()

In [51]:
model_NB.fit(X_train, y_train)

GaussianNB()

In [52]:
y_pred_NB = model_NB.predict(X_test)

In [53]:
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1])

In [54]:
accuracy_score(y_test, y_pred_NB)

0.8089887640449438

In [55]:
confusion_matrix(y_test, y_pred_NB)

array([[88, 21],
       [13, 56]], dtype=int64)

In [56]:
print(classification_report(y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.87      0.81      0.84       109
           1       0.73      0.81      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.80       178
weighted avg       0.82      0.81      0.81       178

In [57]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,class_First,class_Second,class_Third,who_child,who_man,who_woman
0,0,3,1,22,1,0,7,2,1,0,0,1,0,1,0
1,1,1,0,38,1,0,71,0,0,1,0,0,0,0,1
2,1,3,0,26,0,0,7,2,0,0,0,1,0,0,1
3,1,1,0,35,1,0,53,2,0,1,0,0,0,0,1
4,0,3,1,35,0,0,8,2,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,2,1,0,1,0,0,1,0
887,1,1,0,19,0,0,30,2,0,1,0,0,0,0,1
888,0,3,0,29,1,2,23,2,0,0,0,1,0,0,1
889,1,1,1,26,0,0,30,0,1,1,0,0,0,1,0
890,0,3,1,32,0,0,7,1,1,0,0,1,0,1,0

In [58]:
from sklearn.tree import DecisionTreeClassifier

In [59]:
model_DC = DecisionTreeClassifier()

In [60]:
model_DC.fit(X_train_scale, y_train)

DecisionTreeClassifier()

In [61]:
y_pred_DC = model_DC.predict(X_test_scale)

In [62]:
y_pred_DC

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [63]:
accuracy_score(y_test, y_pred_DC)

0.7359550561797753

In [64]:
confusion_matrix(y_test, y_pred_DC)

array([[85, 24],
       [23, 46]], dtype=int64)

In [65]:
print(classification_report(y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.87      0.81      0.84       109
           1       0.73      0.81      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.80       178
weighted avg       0.82      0.81      0.81       178

In [66]:
from sklearn.svm import SVC

In [67]:
model_sm= SVC(kernel='rbf')

In [68]:
model_sm.fit(X_train_scale, y_train)

SVC()

In [69]:
model_sm.predict(X_test_scale)

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [70]:
y_pred_sm = model_sm.predict(X_test_scale)

In [71]:
y_pred_sm

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [72]:
accuracy_score(y_test, y_pred_sm)

0.8314606741573034

In [73]:
confusion_matrix(y_test, y_pred_DC)

array([[85, 24],
       [23, 46]], dtype=int64)

In [74]:
print(classification_report(y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.87      0.81      0.84       109
           1       0.73      0.81      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.80       178
weighted avg       0.82      0.81      0.81       178

In [75]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male,class_First,class_Second,class_Third,who_child,who_man,who_woman
0,0,3,1,22,1,0,7,2,1,0,0,1,0,1,0
1,1,1,0,38,1,0,71,0,0,1,0,0,0,0,1
2,1,3,0,26,0,0,7,2,0,0,0,1,0,0,1
3,1,1,0,35,1,0,53,2,0,1,0,0,0,0,1
4,0,3,1,35,0,0,8,2,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,2,1,0,1,0,0,1,0
887,1,1,0,19,0,0,30,2,0,1,0,0,0,0,1
888,0,3,0,29,1,2,23,2,0,0,0,1,0,0,1
889,1,1,1,26,0,0,30,0,1,1,0,0,0,1,0
890,0,3,1,32,0,0,7,1,1,0,0,1,0,1,0

In [76]:
x= df.drop('survived', axis=1)
y = df['survived']

In [77]:
from sklearn.model_selection import cross_val_score

In [ ]:
scaler = StandardScaler()
x_scled = scaler.fit(x)

In [83]:
scores = cross_val_score(model_sm, x, y, cv=5, scoring='accuracy')

In [84]:
print(scores)

[0.58426966 0.71348315 0.69101124 0.68539326 0.68926554]

In [85]:
print(scores.mean())

0.6726845680187901